export const data = {
  took: 29,
  timed_out: false,
  _shards: {
    total: 5,
    successful: 5,
    skipped: 0,
    failed: 0,
  },
  hits: {
    total: 1140460,
    max_score: 0.82339126,
    hits: [
      {
        _index: 'rwjf',
        _type: '_doc',
        _id: '7695041',
        _score: 0.82339126,
        _source: {
          id_of_project: '5U54GM062116-08',
          year_fiscal_funding: 2008,
          placeName_city_organisation: 'LA JOLLA',
          placeName_country_organisation: 'UNITED STATES',
          placeName_state_organisation: 'CA',
          placeName_zipcode_organisation: '920371000',
          title_of_organisation: 'SCRIPPS RESEARCH INSTITUTE',
          terms_descriptive_project:
            'Analysis, Data;Architecture;Archives;Area;Bio-Informatics;Biochemistry;Bioinformatics;Biology;Bonding;Bonding (Psychology);Bonding, Psychological;Chemistry, Biological;Collaborations;Communities;Complex;Computer Programs;Computer Software Development;Computer Software Engineering;Computer software;Coupled;Data;Data Analyses;Data Banks;Data Bases;Data Collection;Data Set;Databank, Electronic;Databanks;Database, Electronic;Databases;Dataset;Deep;Depth;Development;Development Plans;EC 2.4;Engineering / Architecture;Engineering, Software;Ensure;European;Feedback;Fees;Figs;Figs - dietary;Flexibility;Glycans;Glycoside Transferases;Goals;Grant;Human;Human Resources;Human, General;IT Systems;Individual;Informatics;Information Systems;Information Technology;Information Technology Systems;Infrastructure;International;Internet;Investigators;Japanese;Japanese Population;Java;Maintenance;Maintenances;Mammals, Mice;Man (Taxonomy);Man, Modern;Manpower;Maps;Metabolic Glycosylation;Mice;Mining;Minings;Molecular Weight;Molecular and Cellular Biology;Murine;Mus;Object Attachment;Object Relationship;On-Line Systems;Online Systems;Operation;Operative Procedures;Operative Surgical Procedures;Organization Charts;Pathway interactions;Personal Satisfaction;Phase;Plans, Development;Pliability;Polysaccharides;Position;Positioning Attribute;Process;Programs (PT);Programs [Publication Type];Proteins;Publications;Pyschological Bonding;Range;Research;Research Infrastructure;Research Personnel;Research Resources;Researchers;Resources;Role;Scientific Publication;Software;Software Engineering;Source;Specific qualifier value;Specified;Spinal Column;Spine;Staging;Structure;Surgical;Surgical Interventions;Surgical Procedure;Systems, Data;Technology;Testing;Training;Translating;Translatings;Update;Vertebral column;WWW;Work;backbone;base;carbohydrate structure;clinical data repository;clinical data warehouse;computational tools;computer program/software;computerized tools;data acquisition;data integration;data repository;design;designing;experience;gene product;glycosylation;glycosyltransferase;improved;language translation;member;online computer;organizational structure;pathway;personnel;programs;relational database;social role;surgery;tool;user friendly computer software;user friendly software;user-friendly;web;web based;well-being;world wide web',
          title_of_project: 'Core--Biolnformatics',
          cost_total_project: 0,
          textBody_descriptive_project: '',
          coordinate_of_organisation: {
            lat: '32.8335005',
            lon: '-117.2616203',
          },
          id_iso2_country: 'US',
          id_iso3_country: 'USA',
          id_isoNumeric_country: '840',
          id_of_continent: 'NA',
          currency_total_cost: 'USD',
          terms_mesh_abstract: ['Humans'],
          textBody_abstract_project: 'ABSTRACT NOT PROVIDED',
          booleanFlag_duplicate_abstract: true,
        },
      },
      {
        _index: 'rwjf',
        _type: '_doc',
        _id: '7695043',
        _score: 0.82339126,
        _source: {
          id_of_project: '5U54GM062116-08',
          year_fiscal_funding: 2008,
          placeName_city_organisation: 'LA JOLLA',
          placeName_country_organisation: 'UNITED STATES',
          placeName_state_organisation: 'CA',
          placeName_zipcode_organisation: '920371000',
          title_of_organisation: 'SCRIPPS RESEARCH INSTITUTE',
          terms_descriptive_project:
            'Affinity;Analytical Chemistry;Antibodies;Apanteles kariyai growth blocking peptide;Arts;Biochemistry;Carbohydrates;Cell Communication;Cell Interaction;Cell-to-Cell Interaction;Chemicals;Chemistry, Analytic;Chemistry, Analytical;Chemistry, Biological;Computer Programs;Computer software;DNA Molecular Biology;Development;Ensure;Equipment;Figs;Figs - dietary;Future;GBP;Glycans;Glycolipids;Glycoproteins;Goals;Human Resources;Investigators;JHERP protein, Apanteles kariyai;Laboratories;Laboratory Personnel;Libraries;Ligands;Link;Liquid substance;Manpower;Mediating;Microarray Analysis;Microarray-Based Analysis;Molecular Biology;Moscow;Organic Synthesis;Organization Charts;Peptide Biosynthesis, Ribosomal;Polymers;Polysaccharides;Printing;Production;Programs (PT);Programs [Publication Type];Protein Biosynthesis;Protein Biosynthesis, Ribosomal;Protein Synthesis, Ribosomal;Protein-Carbohydrate Interaction;Range;Reagent;Research Institute;Research Personnel;Research Resources;Researchers;Resources;Robotics;Role;Screening procedure;Slide;Software;Specificity;Structure;Technology;computer program/software;fluid;functional group;growth blocking peptide , Apanteles kariyai;growth blocking peptide, Apanteles kariyai;juvenile hormone esterase repressive peptide, Apanteles kariyai;liquid;microarray technology;organizational structure;personnel;polyacrylamide;programs;protein synthesis;screening;screenings;social role',
          title_of_project: 'Core--Glycan Array Synthesis Core',
          cost_total_project: 0,
          textBody_descriptive_project: '',
          coordinate_of_organisation: {
            lat: '32.8335005',
            lon: '-117.2616203',
          },
          id_iso2_country: 'US',
          id_iso3_country: 'USA',
          id_isoNumeric_country: '840',
          id_of_continent: 'NA',
          currency_total_cost: 'USD',
          terms_mesh_abstract: ['Humans'],
          textBody_abstract_project: 'ABSTRACT NOT PROVIDED',
          booleanFlag_duplicate_abstract: true,
        },
      },
      {
        _index: 'rwjf',
        _type: '_doc',
        _id: '7695046',
        _score: 0.82339126,
        _source: {
          id_of_project: '5U54GM062116-08',
          year_fiscal_funding: 2008,
          placeName_city_organisation: 'LA JOLLA',
          placeName_country_organisation: 'UNITED STATES',
          placeName_state_organisation: 'CA',
          placeName_zipcode_organisation: '920371000',
          title_of_organisation: 'SCRIPPS RESEARCH INSTITUTE',
          terms_descriptive_project:
            'Antibodies;Assay;Autoregulation;Behavior;Binding Proteins;Bioassay;Biologic Assays;Biological Assay;Biological Function;Biological Process;Blood Cell Count;Blood Cell Number;Blood Serum;Body Tissues;California;Cells;Chemistry;Communication;Construction;Consultations;Data Banks;Data Bases;Databank, Electronic;Databanks;Database, Electronic;Databases;Development;EC 2.4;Enzymes;Facility Construction Funding Category;Funding;Genes;Genetic Alteration;Genetic Change;Genetic defect;Glycans;Glycoside Transferases;Goals;Hematology;Hematopoietic;Hemostasis;Hemostatic function;Histology;Homeostasis;Immune;Immune system;Immunologic, Immunochemical;Immunologics;Immunology;Immunology (Including BRMP);Immunology (NCI Program);Intermediary Metabolism;Investigators;Lectin;Ligand Binding Protein;Ligands;Localized;METBL;Mammals, Mice;Measurement;Mediating;Metabolic;Metabolic Processes;Metabolism;Mice;Mice, Transgenic;Morphology;Mouse Strains;Murine;Mus;Mutation;Phenotype;Physiologic;Physiological;Physiological Homeostasis;Physiology;Polysaccharides;Programs (PT);Programs [Publication Type];Protein-Carbohydrate Interaction;Reagent;Research;Research Personnel;Research Resources;Researchers;Resources;Science of Chemistry;Screening procedure;Serum;Staining method;Stainings;Stains;Testing;Tissues;Transgenic Mice;Universities;body system, allergic/immunologic;cell type;clinical data repository;clinical data warehouse;data repository;design;designing;experiment;experimental research;experimental study;genome mutation;glycosyltransferase;in vivo;organ system, allergic/immunologic;programs;protein function;relational database;research study;response;screening;screenings',
          title_of_project: 'Core--Mouse Phenotype',
          cost_total_project: 0,
          textBody_descriptive_project: '',
          coordinate_of_organisation: {
            lat: '32.8335005',
            lon: '-117.2616203',
          },
          id_iso2_country: 'US',
          id_iso3_country: 'USA',
          id_isoNumeric_country: '840',
          id_of_continent: 'NA',
          currency_total_cost: 'USD',
          terms_mesh_abstract: ['Humans'],
          textBody_abstract_project: 'ABSTRACT NOT PROVIDED',
          booleanFlag_duplicate_abstract: true,
        },
      },
      {
        _index: 'rwjf',
        _type: '_doc',
        _id: '7694415',
        _score: 0.82339126,
        _source: {
          id_of_project: '5U54CA112967-05',
          year_fiscal_funding: 2008,
          placeName_city_organisation: 'CAMBRIDGE',
          placeName_country_organisation: 'UNITED STATES',
          placeName_state_organisation: 'MA',
          placeName_zipcode_organisation: '02139',
          title_of_organisation: 'MASSACHUSETTS INSTITUTE OF TECHNOLOGY',
          terms_descriptive_project:
            'Animals;Award;Bio-Informatics;Bioinformatics;Biological;Biology;Budgets;Cancer Biology;Center for Cancer Research;Computer Sciences, Other;Computer Simulation;Computerized Models;Discipline;Electrical Engineering;Endowment;Engineering;Engineerings;Ensure;Faculty;Fostering;Funding;Funding Mechanisms;Institutes;Math Models;Mathematical Model Simulation;Mathematical Models and Simulations;Mathematics;Mission;Modeling;Models, Computer;Molecular;NCI Center for Cancer Research;Numbers;Pilot Projects;Programs (PT);Programs [Publication Type];Research;Research Support;Review Committee;Salaries;Scientist;Simulation, Computer based;Sorting - Cell Movement;Students;System;System, LOINC Axis 4;Systems Biology;Training;Wages;Work;anticancer research;base;cancer research;computational modeling;computational models;computational simulation;computer based models;computerized modeling;computerized simulation;experience;in silico;interest;mathematical model;mathematical modeling;novel;pilot study;programs;size;sorting;success;virtual simulation',
          title_of_project: 'PILOT PROJECTS',
          cost_total_project: 0,
          textBody_descriptive_project: '',
          coordinate_of_organisation: {
            lat: '42.3750997',
            lon: '-71.1056157',
          },
          id_iso2_country: 'US',
          id_iso3_country: 'USA',
          id_isoNumeric_country: '840',
          id_of_continent: 'NA',
          currency_total_cost: 'USD',
          terms_mesh_abstract: ['Humans'],
          textBody_abstract_project: 'Abstract not provided.',
        },
      },
      {
        _index: 'rwjf',
        _type: '_doc',
        _id: '7726914',
        _score: 0.82339126,
        _source: {
          id_of_project: '5P01CA092625-07',
          year_fiscal_funding: 2007,
          placeName_city_organisation: 'BOSTON',
          placeName_country_organisation: 'UNITED STATES',
          placeName_state_organisation: 'MA',
          placeName_zipcode_organisation: '02115',
          title_of_organisation: 'DANA-FARBER CANCER INSTITUTE',
          terms_descriptive_project: '',
          title_of_project: 'Administrative',
          cost_total_project: 0,
          textBody_descriptive_project: '',
          coordinate_of_organisation: {
            lat: '42.3602534',
            lon: '-71.0582912',
          },
          id_iso2_country: 'US',
          id_iso3_country: 'USA',
          id_isoNumeric_country: '840',
          id_of_continent: 'NA',
          currency_total_cost: 'USD',
          terms_mesh_abstract: ['Humans'],
          textBody_abstract_project:
            'The Administrative Core will provide scientific, administrative and financial oversight and assistance to the projects and cores of the PO1.',
        },
      },
      {
        _index: 'rwjf',
        _type: '_doc',
        _id: '7726923',
        _score: 0.82339126,
        _source: {
          id_of_project: '5P01CA092625-08',
          year_fiscal_funding: 2008,
          placeName_city_organisation: 'BOSTON',
          placeName_country_organisation: 'UNITED STATES',
          placeName_state_organisation: 'MA',
          placeName_zipcode_organisation: '02115',
          title_of_organisation: 'DANA-FARBER CANCER INSTITUTE',
          terms_descriptive_project:
            'Gender;Goals;Individual;Investigators;Minority;Monitor;Participant;Progress Reports;Regulation;Reporting;Reports, Progress;Research Personnel;Researchers;Vertebrate Animals;Vertebrates;base;human subject;vertebrata',
          title_of_project: 'Administrative',
          cost_total_project: 0,
          textBody_descriptive_project: '',
          coordinate_of_organisation: {
            lat: '42.3602534',
            lon: '-71.0582912',
          },
          id_iso2_country: 'US',
          id_iso3_country: 'USA',
          id_isoNumeric_country: '840',
          id_of_continent: 'NA',
          currency_total_cost: 'USD',
          terms_mesh_abstract: ['Humans'],
          textBody_abstract_project:
            'The Administrative Core will provide scientific, administrative and financial oversight and assistance to the projects and cores of the PO1.',
          booleanFlag_duplicate_abstract: true,
        },
      },
      {
        _index: 'rwjf',
        _type: '_doc',
        _id: '6591049',
        _score: 0.82339126,
        _source: {
          id_of_project: '5P20CA091411-02',
          year_fiscal_funding: 2002,
          placeName_city_organisation: 'NEW YORK',
          placeName_country_organisation: 'UNITED STATES',
          placeName_state_organisation: 'NY',
          placeName_zipcode_organisation: '112102850',
          title_of_organisation: 'BROOKLYN COLLEGE',
          date_start_project: '2002-06-01',
          date_end_project: '2003-05-31',
          terms_descriptive_project:
            'smoking;psychological stressor;racial /ethnic difference;gender difference;tobacco abuse;substance abuse related behavior;nicotine;nitrosamines;prejudice;African American;caucasian American;behavioral /social science research tag;clinical research;human subject;',
          title_of_project:
            'EXPOSURE TO CARCINOGENS IN TOBACCO SMOKE--ROLE OF RACE, GENDER AND STRESS',
          cost_total_project: 0,
          textBody_descriptive_project: '',
          coordinate_of_organisation: {
            lat: '30.8385202',
            lon: '-87.2008048',
          },
          id_iso2_country: 'US',
          id_iso3_country: 'USA',
          id_isoNumeric_country: '840',
          id_of_continent: 'NA',
          currency_total_cost: 'USD',
          terms_mesh_abstract: ['Humans'],
          textBody_abstract_project: 'ABSTRACT NOT AVAILABLE',
        },
      },
      {
        _index: 'rwjf',
        _type: '_doc',
        _id: '7188012',
        _score: 0.82339126,
        _source: {
          id_of_project: '5P30DK047754-13',
          year_fiscal_funding: 2006,
          placeName_city_organisation: 'SEATTLE',
          placeName_country_organisation: 'UNITED STATES',
          placeName_state_organisation: 'WA',
          placeName_zipcode_organisation: '981959472',
          title_of_organisation: 'UNIVERSITY OF WASHINGTON',
          terms_descriptive_project: '',
          title_of_project: 'Pilot and Feasibility Program',
          cost_total_project: 0,
          textBody_descriptive_project: '',
          coordinate_of_organisation: {
            lat: '47.6038321',
            lon: '-122.3300624',
          },
          id_iso2_country: 'US',
          id_iso3_country: 'USA',
          id_isoNumeric_country: '840',
          id_of_continent: 'NA',
          currency_total_cost: 'USD',
          terms_mesh_abstract: ['Humans'],
          textBody_abstract_project: 'ABSTRACT NOT PROVIDED',
          booleanFlag_duplicate_abstract: true,
        },
      },
      {
        _index: 'rwjf',
        _type: '_doc',
        _id: '7691792',
        _score: 0.82339126,
        _source: {
          id_of_project: '5U19CA113297-05',
          year_fiscal_funding: 2009,
          placeName_city_organisation: 'MADISON',
          placeName_country_organisation: 'UNITED STATES',
          placeName_state_organisation: 'WI',
          placeName_zipcode_organisation: '537151218',
          title_of_organisation: 'UNIVERSITY OF WISCONSIN-MADISON',
          date_start_project: '2005-06-21',
          date_end_project: '2010-04-30',
          terms_descriptive_project: '',
          title_of_project:
            'UWCCC National Cooperative Drug Discovery Group for Can*',
          cost_total_project: 1038617,
          textBody_descriptive_project: '',
          coordinate_of_organisation: {
            lat: '43.074761',
            lon: '-89.3837613',
          },
          id_iso2_country: 'US',
          id_iso3_country: 'USA',
          id_isoNumeric_country: '840',
          id_of_continent: 'NA',
          currency_total_cost: 'USD',
          terms_mesh_abstract: ['Humans'],
          textBody_abstract_project: ' DESCRIPTION (provided by applicant) 4 ',
        },
      },
      {
        _index: 'rwjf',
        _type: '_doc',
        _id: '7695037',
        _score: 0.82339126,
        _source: {
          id_of_project: '5U54GM062116-08',
          year_fiscal_funding: 2008,
          placeName_city_organisation: 'LA JOLLA',
          placeName_country_organisation: 'UNITED STATES',
          placeName_state_organisation: 'CA',
          placeName_zipcode_organisation: '920371000',
          title_of_organisation: 'SCRIPPS RESEARCH INSTITUTE',
          terms_descriptive_project:
            'Animals;Bacteria;Biology;Carbohydrates;Complex;Glass;Goals;Human;Human, General;Immobilization;Man (Taxonomy);Man, Modern;Modification;Oligo;Oligonucleotides;Research Resources;Resources;Slide;Structure;abstracting;functional genomics;immobilization of body part;orthopedic freezing;tool',
          title_of_project:
            'Isolation &characterization of bacterial carbohydrates for glycoarray',
          cost_total_project: 0,
          textBody_descriptive_project: '',
          coordinate_of_organisation: {
            lat: '32.8335005',
            lon: '-117.2616203',
          },
          id_iso2_country: 'US',
          id_iso3_country: 'USA',
          id_isoNumeric_country: '840',
          id_of_continent: 'NA',
          currency_total_cost: 'USD',
          terms_mesh_abstract: ['Humans'],
          textBody_abstract_project: 'ABSTRACT NOT PROVIDED',
          booleanFlag_duplicate_abstract: true,
        },
      },
    ],
  },
};
